main ::= NO_DIFF_MSG
main ::= diff_list

diff_list ::= diff
diff_list ::= diff diff_list

diff ::= DIFF_PHRASE FILE FILE NEWLINE DELETED_PHRASE MODE NEWLINE INDEX_KW HASH DOTDOT_KW HASH NEWLINE
diff ::= DIFF_PHRASE FILE FILE NEWLINE INDEX_KW HASH DOTDOT_KW HASH MODE NEWLINE MMM_KW FILE NEWLINE PPP_KW FILE NEWLINE diff_header diff_body ENDDIFF

diff_header ::= ATAT_KW M_KW FIRST_LINE_MINUS COMMA_KW SECOND_LINE_MINUS P_KW FIRST_LINE_PLUS COMMA_KW SECOND_LINE_PLUS ATAT_KW NEWLINE

diff_body ::= diff_line
diff_body ::= diff_body diff_line

diff_line ::= SIGN DIFFLINE
