main ::= NO_DIFF_MSG
main ::= diff_list

diff_list ::= diff
diff_list ::= diff diff_list

diff ::= DIFF_PHRASE FILE FILE NEWLINE DELETED_PHRASE MODE NEWLINE INDEX_KW HASH DOTDOT_KW HASH NEWLINE
diff ::= DIFF_PHRASE FILE FILE NEWLINE INDEX_KW HASH DOTDOT_KW HASH MODE NEWLINE MMM_KW FILE NEWLINE PPP_KW FILE NEWLINE diff_header diff_body ENDDIFF

diff_header ::= THREE_MINUS FILE NEWLINE THREE_PLUS FILE NEWLINE ATAT MINUS FIRST_LINE_MINUS COMMA SECOND_LINE_MINUS PLUS FIRST_LINE_PLUS COMMA SECOND_LINE_PLUS ATAT NEWLINE

diff_body ::= diff_line
diff_body ::= diff_body diff_line

diff_line ::= SIGN DIFFLINE NEWLINE
